defaults: &type
   type: SEA

defaults: &actuator_TBM-60-25-B
   Bm: 0.0000252
   phim: 0.0000512

defaults: &actuator_TBM-76-15-B
   Bm: 0.0000304
   phim: 0.0000578

defaults: &actuator_TBM-60-13-B
   Bm: 0.0000141
   phim: 0.0000195

defaults: &actuator_TBM-76-15-A
   Bm: 0.0000304
   phim: 0.0000578

defaults: &actuator_RBE-1211
   Bm: 0.00000847
   phim: 0.00002

defaults: &actuator_RBE-1210
   Bm: 0.00000515
   phim: 0.00000877

defaults: &motor_upper_body_1
   B: 1.181
   phim: 0.0000512

defaults: &motor_upper_body_2
   B: 0.846
   phim: 0.0000195

defaults: &motor_wrist_1
   B: 0.163
   phim: 0.00002

defaults: &motor_wrist_2
   B: 0.126
   phim: 0.00000877

defaults: &gear_CPL20
   nu: 160

defaults: &gear_CPL17
   nu: 120

defaults: &gear_CPL25
   nu: 160

defaults: &spring_hip_yaw
   Ks: 80000
   D: 2.0

defaults: &spring_hip_pitch
   Ks: 80000
   D: 2.0

defaults: &spring_knee_pitch
   Ks: 80000
   D: 2.0

defaults: &spring_ankle_pitch
   Ks: 80000
   D: 2.0

defaults: &spring_ankle_yaw
   Ks: 40000
   D: 1.0

defaults: &spring_wheel
   Ks: 40000
   D: 1.0

defaults: &springT1
   Ks: 6000
   D: 0.05

defaults: &springT2
   Ks: 9400
   D: 0.1

defaults: &springT3
   Ks: 10000
   D: 0.1

defaults: &gear_160
   nu: 160

defaults: &gear_100
   nu: 100

defaults: &torque_limit_upper_body
   Torque_limit: 147

defaults: &torque_limit_wrist_1
   Torque_limit: 55

defaults: &torque_limit_wrist_2
   Torque_limit: 27

defaults: &torque_limit_leg
   Torque_limit: 304

defaults: &torque_limit_ankle_1
   Torque_limit: 147

defaults: &torque_limit_ankle_2
   Torque_limit: 35

defaults: &torque_limit_6025B-20
   Torque_limit: 147

defaults: &torque_limit_6013B-20
   Torque_limit: 147

defaults: &torque_limit_1211-17
   Torque_limit: 77

defaults: &torque_limit_1210-17
   Torque_limit: 33

defaults: &torque_limit_7615A-25
   Torque_limit: 314

defaults: &torque_limit_7615B-25
   Torque_limit: 275

defaults: &torque_limit_6013B_17
   Torque_limit: 86


centauro:
   actuators:
      hip_yaw_1:
         <<: *type
         <<: *spring_hip_yaw
         <<: *actuator_TBM-60-25-B
         <<: *gear_CPL20
         <<: *torque_limit_leg
      hip_yaw_2:
         <<: *type
         <<: *spring_hip_yaw
         <<: *actuator_TBM-60-25-B
         <<: *gear_CPL20
         <<: *torque_limit_leg
      hip_yaw_3:
         <<: *type
         <<: *spring_hip_yaw
         <<: *actuator_TBM-60-25-B
         <<: *gear_CPL20
         <<: *torque_limit_leg
      hip_yaw_4:
         <<: *type
         <<: *spring_hip_yaw
         <<: *actuator_TBM-60-25-B
         <<: *gear_CPL20
         <<: *torque_limit_leg
      hip_pitch_1:
         <<: *type
         <<: *spring_hip_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      hip_pitch_2:
         <<: *type
         <<: *spring_hip_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      hip_pitch_3:
         <<: *type
         <<: *spring_hip_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      hip_pitch_4:
         <<: *type
         <<: *spring_hip_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      knee_pitch_1:
         <<: *type
         <<: *spring_knee_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      knee_pitch_2:
         <<: *type
         <<: *spring_knee_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      knee_pitch_3:
         <<: *type
         <<: *spring_knee_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      knee_pitch_4:
         <<: *type
         <<: *spring_knee_pitch
         <<: *actuator_TBM-76-15-B
         <<: *gear_CPL25
         <<: *torque_limit_leg
      ankle_pitch_1:
         <<: *type
         <<: *spring_ankle_pitch
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_ankle_1
      ankle_pitch_2:
         <<: *type
         <<: *spring_ankle_pitch
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_ankle_1
      ankle_pitch_3:
         <<: *type
         <<: *spring_ankle_pitch
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_ankle_1
      ankle_pitch_4:
         <<: *type
         <<: *spring_ankle_pitch
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_1
      ankle_yaw_1:
         <<: *type
         <<: *spring_ankle_yaw
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      ankle_yaw_2:
         <<: *type
         <<: *spring_ankle_yaw
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      ankle_yaw_3:
         <<: *type
         <<: *spring_ankle_yaw
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      ankle_yaw_4:
         <<: *type
         <<: *spring_ankle_yaw
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      j_wheel_1:
         <<: *type
         <<: *spring_wheel
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      j_wheel_2:
         <<: *type
         <<: *spring_wheel
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      j_wheel_3:
         <<: *type
         <<: *spring_knee_pitch
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      j_wheel_4:
         <<: *type
         <<: *spring_wheel
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      torso_yaw:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_upper_body
      neck_yaw:
         <<: *type
         <<: *springT1
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      neck_pitch:
         <<: *type
         <<: *springT1
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      neck_velodyne:
         <<: *type
         <<: *springT1
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_ankle_2
      j_arm1_1:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm1_2:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm1_3:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_2
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm1_4:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_2
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm1_5:
         <<: *type
         <<: *springT2
         <<: *motor_wrist_1
         <<: *gear_100
         <<: *torque_limit_wrist_1
      j_arm1_6:
         <<: *type
         <<: *springT2
         <<: *motor_wrist_1
         <<: *gear_100
         <<: *torque_limit_wrist_1
      j_arm1_7:
         <<: *type
         <<: *springT3
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_wrist_2
      j_arm2_1:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm2_2:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_1
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm2_3:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_2
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm2_4:
         <<: *type
         <<: *springT1
         <<: *motor_upper_body_2
         <<: *gear_160
         <<: *torque_limit_upper_body
      j_arm2_5:
         <<: *type
         <<: *springT2
         <<: *motor_wrist_1
         <<: *gear_100
         <<: *torque_limit_wrist_1
      j_arm2_6:
         <<: *type
         <<: *springT2
         <<: *motor_wrist_1
         <<: *gear_100
         <<: *torque_limit_wrist_1
      j_arm2_7:
         <<: *type
         <<: *springT3
         <<: *motor_wrist_2
         <<: *gear_100
         <<: *torque_limit_wrist_2
