left_arm:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 1
  moveit_player_rotspace: "full"
  nimbro_ik:
    ik_type: full
    sdls: true
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"

right_arm:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 1
  moveit_player_rotspace: "full"
  nimbro_ik:
    ik_type: full
    sdls: true
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"

front_left_ankle:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: without_roll
  nimbro_ik:
    ik_type: position_and_x_axis
    sdls: false
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"
    
front_right_ankle:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: without_roll
  nimbro_ik:
    ik_type: position_and_x_axis
    sdls: false
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"
        
back_right_ankle:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: without_roll
  nimbro_ik:
    ik_type: position_and_x_axis
    sdls: false
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"

back_left_ankle:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: without_roll
  nimbro_ik:
    ik_type: position_and_x_axis
    sdls: false
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"
