#front_left_leg:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
#front_right_leg:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
#back_right_leg:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
#back_left_leg:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
left_arm:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
#left_arm_and_torso:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
right_arm:
  kinematics_solver: nimbro_ik::IKSolver
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  moveit_player_rotspace: "full"
  nimbro_ik:
    ik_type: full
    cost_functions:
      - type: "nimbro_ik::cost::ConvenientPose"
        state: "convenient"
#right_arm_and_torso:
  #kinematics_solver: nimbro_ik::IKSolver
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
