<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- macro legs -->
<xacro:macro name="centauro_leg" params="leg_num origin_x origin_y">

<link name="hip1_${leg_num}">
	<inertial>
		<origin xyz="${Leg_1_x} ${origin_x*origin_y*Leg_1_y} ${Leg_1_z}" />
		<mass value="${Leg_1_mass}"/> <!-- org: 2 -->
		<inertia ixx="${Leg_1_xx}" ixy="${origin_x*origin_y*Leg_1_xy}" ixz="${Leg_1_xz}" iyy="${Leg_1_yy}" iyz="${origin_x*origin_y*Leg_1_yz}" izz="${Leg_1_zz}"/>
		<!-- <inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/> -->
	</inertial>
      <visual>
         <xacro:visual_model.leg1 />
         <material name="dark_grey"/>
      </visual>
	
      <collision>
         <xacro:collision_model.leg1 />
      </collision>

</link>

<link name="hip2_${leg_num}">
	<inertial>
		<origin xyz="${Leg_2_x} ${Leg_2_y} ${Leg_2_z}"/>	
		<mass value="${Leg_2_mass}"/> <!-- org: 4.5 -->
		<inertia ixx="${Leg_2_xx}" ixy="${Leg_2_xy}" ixz="${Leg_2_xz}" iyy="${Leg_2_yy}" iyz="${Leg_2_yz}" izz="${Leg_2_zz}"/> 
		<!-- <inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/> -->
	</inertial>

      <visual>
         <xacro:visual_model.leg2 />
      </visual>
	
      <collision>
         <xacro:collision_model.leg2 />
      </collision>

</link>

<link name="knee_${leg_num}">
	<inertial>
		<origin xyz="${Leg_3_x} ${Leg_3_y} ${Leg_3_z}"/>
		<mass value="${Leg_3_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Leg_3_xx}" ixy="${Leg_3_xy}" ixz="${Leg_3_xz}" iyy="${Leg_3_yy}" iyz="${Leg_3_yz}" izz="${Leg_3_zz}"/>
	<!--	<inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>  -->
	</inertial>

      <visual>
         <xacro:visual_model.leg3 />
         <material name="dark_grey"/>
      </visual>
	
      <collision>
         <xacro:collision_model.leg3 />
      </collision>
</link>

<link name="ankle1_${leg_num}">
	<inertial>
		<origin xyz="${Ankle_1_x} ${Ankle_1_y} ${Ankle_1_z}"/>
		<mass value="${Ankle_1_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Ankle_1_xx}" ixy="${Ankle_1_xy}" ixz="${Ankle_1_xz}" iyy="${Ankle_1_yy}" iyz="${Ankle_1_yz}" izz="${Ankle_1_zz}"/>
	<!--	<inertia ixx="0.01" ixy="0.01" ixz="0.01" iyy="0.01" iyz="0.01" izz="0.01"/>  -->
	</inertial>

      <visual>
         <xacro:visual_model.ankle1 />
      </visual>
	
      <collision>
         <xacro:collision_model.ankle1 />
      </collision>
</link>

<link name="ankle2_${leg_num}">
	<inertial>
		<origin xyz="${Ankle_2_x} ${Ankle_2_y} ${Ankle_2_z}"/>
		<mass value="${Ankle_2_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Ankle_2_xx}" ixy="${Ankle_2_xy}" ixz="${Ankle_2_xz}" iyy="${Ankle_2_yy}" iyz="${Ankle_2_yz}" izz="${Ankle_2_zz}"/>

	</inertial>

      <visual>
         <xacro:visual_model.ankle2 />
         <material name="dark_grey"/>
      </visual>
	
      <collision>
         <xacro:collision_model.ankle2 />
      </collision>
</link>

<link name="wheel_${leg_num}">
	<inertial>
		<origin xyz="${Wheel_x} ${Wheel_y} ${Wheel_z}"/>
		<mass value="${Wheel_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Wheel_xx}" ixy="${Wheel_xy}" ixz="${Wheel_xz}" iyy="${Wheel_yy}" iyz="${Wheel_yz}" izz="${Wheel_zz}"/>
	</inertial>

      <visual>
         <xacro:visual_model.wheel />
         <material name="black"/>
      </visual>
	
      <collision>
         <xacro:collision_model.wheel />
      </collision>
</link> 

<joint name="hip_yaw_${leg_num}" type="revolute">
	<parent link="pelvis"/>
	<child link="hip1_${leg_num}"/>
	<origin xyz="${origin_x*Leg_1_Ox} ${origin_y*Leg_1_Oy} ${Leg_1_Oz}" rpy="${Leg_1_roll} ${Leg_1_pitch} ${PI/2-origin_x*PI/2+origin_x*origin_y*Leg_1_yaw}"/>
	<axis xyz="0 0 1"/>
        <limit lower="${hip_yaw_lower[leg_num-1]}" upper="${hip_yaw_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>

<joint name="hip_pitch_${leg_num}" type="revolute">
	<parent link="hip1_${leg_num}"/>
	<child link="hip2_${leg_num}"/>
	<origin xyz="${Leg_2_Ox} ${Leg_2_Oy} ${Leg_2_Oz}" rpy="${Leg_2_roll} ${Leg_2_pitch} ${origin_x*origin_y*Leg_2_yaw-origin_x*origin_y*PI/2 + PI/2}"/>
	<axis xyz="0 0 1"/>
        <limit lower="${hip_pitch_lower[leg_num-1]}" upper="${hip_pitch_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>

<joint name="knee_pitch_${leg_num}" type="revolute">
	<parent link="hip2_${leg_num}"/>
	<child link="knee_${leg_num}"/>
	<origin xyz="${Leg_3_Ox} ${Leg_3_Oy} ${Leg_3_Oz}" rpy="${Leg_3_roll} ${Leg_3_pitch} ${Leg_3_yaw}"/>
	<axis xyz="0 0 1"/>
        <limit lower="${knee_pitch_lower[leg_num-1]}" upper="${knee_pitch_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>

<joint name="ankle_pitch_${leg_num}" type="revolute">
	<parent link="knee_${leg_num}"/>
	<child link="ankle1_${leg_num}"/>
	<origin xyz="${Ankle_1_Ox} ${Ankle_1_Oy} ${Ankle_1_Oz}" rpy="${Ankle_1_roll} ${Ankle_1_pitch} ${Ankle_1_yaw}"/>
	<axis xyz="0 0 1"/>
        <limit lower="${ankle_pitch_lower[leg_num-1]}" upper="${ankle_pitch_upper[leg_num-1]}" effort="${motor_B_effort}" velocity="${motor_B_velocity}"/> <!-- 98 Nm, 1 rad/s-->
</joint>

<joint name="ankle_yaw_${leg_num}" type="revolute">
	<parent link="ankle1_${leg_num}"/>
	<child link="ankle2_${leg_num}"/>
	<origin xyz="${Ankle_2_Ox} ${Ankle_2_Oy} ${Ankle_2_Oz}" rpy="${Ankle_2_roll} ${Ankle_2_pitch} ${Ankle_2_yaw}"/>
	<axis xyz="0 0 1"/>
        <limit lower="${ankle_yaw_lower[leg_num-1]}" upper="${ankle_yaw_upper[leg_num-1]}" effort="${motor_C_effort}" velocity="${motor_C_velocity}"/>  <!-- 23 Nm, 1 rad/s-->
</joint>

<joint name="j_wheel_${leg_num}" type="continuous">
	<parent link="ankle2_${leg_num}"/>
	<child link="wheel_${leg_num}"/>
	<origin xyz="${Wheel_Ox} ${Wheel_Oy} ${Wheel_Oz}" rpy="${Wheel_roll} ${Wheel_pitch} ${Wheel_yaw}"/>
	<axis xyz="0 0 1"/>
        <limit  effort="${motor_C_effort}" velocity="${motor_C_velocity}"/>  <!-- 23 Nm, 1 rad/s-->
</joint>

<!--
<joint name="ft_foot_${leg_num}_joint" type="fixed">
  <parent link="knee_${leg_num}"/>
  <child link="ft_foot_${leg_num}"/>
  <origin xyz="0 0 -0.3" rpy="0 0 0"/>
</joint>
-->
<!-- actuators -->
<xacro:if	value="${leg_actuators}">
	<xacro:position_actuator joint="hip_yaw_${leg_num}" /> 
	<xacro:position_actuator joint="hip_pitch_${leg_num}" /> 
	<xacro:position_actuator joint="knee_pitch_${leg_num}"  /> 
	<xacro:position_actuator joint="ankle_pitch_${leg_num}"  /> 
	<xacro:position_actuator joint="ankle_yaw_${leg_num}"  /> 
	<xacro:position_actuator joint="j_wheel_${leg_num}"  />  
</xacro:if>
<!-- /actuators -->

</xacro:macro>
<!-- /macro legs -->

</robot>
